# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - microjoinOdoo

on:
  push:
    branches:
      - 18.0
  workflow_dispatch:

jobs:
  build-and-deploy:
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    env:
      AZURE_WEBAPP_NAME: 'microjoinOdoo'     # set this to your application's name
      WORKING_DIRECTORY: '.'        # set this to the path to your path of working directory inside github repository, defaults to the repository root
      PYTHON_VERSION: '3.12'
      STARTUP_COMMAND: 'python odoo-bin -r ${{ secrets.DB_USER }} -w ${{ secrets.DB_PASSWORD }} --addons-path=addons -d mydb --db_host=${{ secrets.DB_HOST}}'
      
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          
      - name: Install ldap
        run: sudo apt install -y libldap2-dev libsasl2-dev python3-dev build-essential
        
      - name: Install dependencias-previas
        run: pip install setuptools wheel
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        

      # Azure login
      - uses: azure/login@v1
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS_GITHUB_SECRET }}
      - uses: azure/appservice-settings@v1
        with:
         app-name: ${{ env.AZURE_WEBAPP_NAME }}
         mask-inputs: false
         general-settings-json: '{"linuxFxVersion": "PYTHON|${{ env.PYTHON_VERSION }}"}' #'General configuration settings as Key Value pairs'
      # deploy web app
      - uses: azure/webapps-deploy@v2
        with:
         app-name: ${{ env.AZURE_WEBAPP_NAME }}
         package: ${{ env.WORKING_DIRECTORY }}
         startup-command: ${{ env.STARTUP_COMMAND }}
      # Azure logout
      - name: logout
        run: |
         az logout

        

        

