name: Build and Deploy Python App to Azure Web App

on:
  push:
    branches:
      - 18.0  # La rama que deseas usar para activar este flujo de trabajo
  workflow_dispatch:  # Permite disparar el flujo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Requerido para `actions/checkout`

    steps:
      # Paso 1: Checkout del código
      - uses: actions/checkout@v4

      # Paso 2: Configurar la versión de Python
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Paso 3: Crear y activar el entorno virtual
      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          
      # Paso 4: Instalar dependencias necesarias para compilar python-ldap
      - name: Install ldap dependencies
        run: sudo apt install -y libldap2-dev libsasl2-dev python3-dev build-essential

      # Paso 5: Instalar dependencias previas (como setuptools y wheel)
      - name: Install build dependencies
        run: pip install setuptools wheel

      # Paso 6: Instalar las dependencias de tu aplicación
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Paso 7: (Opcional) Ejecutar pruebas si las tienes
      # - name: Run tests
      #   run: pytest

      # Paso 8: Empacar el artefacto para el despliegue
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      # Paso 9: Subir el artefacto a la siguiente etapa (deploy)
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # Paso 1: Descargar el artefacto del trabajo de construcción
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      # Paso 2: Descomprimir el artefacto para el despliegue
      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Paso 3: Nos logueamos, desplegamos e iniciamos la aplicacion
      - name: Logueo en azure, despliegue e inicializacion de la aplicacion
        uses: Azure/cli@v2.1.0
        with:
          azcliversion: '2.27.0'
          inlineScript: |
            az login --service-principal -u ${{ secrets.AZURE_APP_ID }} -p ${{ secrets.AZURE_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT_ID }}
            az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            az webapp deploy --resource-group ${{ secrets.RESOURCE_GROUP }} --name ${{ secrets.APP_NAME }} --src-path ./release.zip --timeout 1800
            az webapp config appsettings set --resource-group ${{ secrets.RESOURCE_GROUP }} --name ${{ secrets.APP_NAME }} --settings WEBSITE_STARTUP_COMMAND="python odoo-bin -r ${{ secrets.DB_USER }} -w ${{ secrets.DB_PASSWORD }} --addons-path=addons -d mydb --db_host=${{ secrets.DB_HOST }}"
            az webapp restart --resource-group ${{ secrets.RESOURCE_GROUP }} --name ${{ secrets.APP_NAME }}

          
